/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import clases.*;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Matul <https://github.com/MigueMat4>
 */
public class frmMain extends javax.swing.JFrame {
    
    Digimon peleador1, peleador2; // digimons que van a pelear
    String[] columnas = {"Nombre", "Nivel"}; // columnas para la tabla
    DefaultTableModel model = new DefaultTableModel(columnas, 0); // tabla a usar
    DigiWorld yggdrasill; // clase para conectarse a la API y descargar el listado de objetos
    RumbleArena estadio; // clase para elegir a los digimon que van a pelar, carga la imagen de ellos
    Reloj reloj = new Reloj(); // objeto para la hora del sistema. ¡No modificar!

    /**
     * Creates new form frmMain
     */

    public frmMain() {
        initComponents();
        this.setLocationRelativeTo(this);
        tblDigimon.setModel(model); // diseña la tabla en base a las columnas definidas
        btnElegir.setEnabled(false); // no se puede batallar si no hay digimons peleadores
        reloj.start(); // objeto iniciado para la hora del sistema. ¡No modificar!}
       batallar.setEnabled(false);
jScrollPane1.setOpaque(false);             
jScrollPane1.getViewport().setOpaque(false);
tblDigimon.setShowGrid(false);

             
    }
    
    // clase para elegir a los peleadores
    public class RumbleArena {
        public void elegirDigimon() {
            btnElegir.setEnabled(false);
            btnElegir.setEnabled(false);
            System.out.println("Eligiendo a los combatientes...");
            // código para elegir al primer peleador
            int digielecto1 = (int) ((Math.random() * ((yggdrasill.getDigimons().size() - 1) - 0)) + 0);
            int digielecto2 = (int) ((Math.random() * ((yggdrasill.getDigimons().size() - 1) - 0)) + 0);
            peleador1 = yggdrasill.getDigimons().get(digielecto1);
            peleador2 = yggdrasill.getDigimons().get(digielecto2);
            try {
                URL url = new URL(peleador1.getImg());
                Image img = ImageIO.read(url);
                img = img.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);
                lblDigimon1.setIcon(new ImageIcon(img));
                
                URL url2 = new URL(peleador2.getImg());
                Image img2 = ImageIO.read(url2);
                img2 = img2.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);
                lblDigimon2.setIcon(new ImageIcon(img2));
            } catch (MalformedURLException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            lblDigimon1.setText(peleador1.getName());
            lblDigimon2.setText(peleador2.getName());
            // código para elegir al segundo peleador
            // <Inserte su código aquí>
            System.out.println("¡Peladores listos para la batalla!");
            btnElegir.setEnabled(true);
            batallar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDigimon = new javax.swing.JTable();
        batallar = new javax.swing.JButton();
        lblDigimon1 = new javax.swing.JLabel();
        lblDigimon2 = new javax.swing.JLabel();
        lblHH = new javax.swing.JLabel();
        lblMM = new javax.swing.JLabel();
        lblSS = new javax.swing.JLabel();
        btnElegir = new javax.swing.JButton();
        btnGetDigimon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Digi App");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 10));

        tblDigimon.setBackground(new java.awt.Color(0, 0, 0));
        tblDigimon.setForeground(new java.awt.Color(255, 255, 255));
        tblDigimon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDigimon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 560, 114));

        batallar.setBackground(new java.awt.Color(0, 0, 153));
        batallar.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        batallar.setForeground(new java.awt.Color(255, 255, 255));
        batallar.setText("Batallar");
        batallar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        batallar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batallarActionPerformed(evt);
            }
        });
        getContentPane().add(batallar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 100, 40));

        lblDigimon1.setForeground(new java.awt.Color(255, 255, 255));
        lblDigimon1.setText("Digimon 1");
        getContentPane().add(lblDigimon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        lblDigimon2.setForeground(new java.awt.Color(255, 255, 255));
        lblDigimon2.setText("Digimon 2");
        getContentPane().add(lblDigimon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        lblHH.setForeground(new java.awt.Color(255, 255, 255));
        lblHH.setText("HH:");
        getContentPane().add(lblHH, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        lblMM.setForeground(new java.awt.Color(255, 255, 255));
        lblMM.setText("MM:");
        getContentPane().add(lblMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        lblSS.setForeground(new java.awt.Color(255, 255, 255));
        lblSS.setText("SS");
        getContentPane().add(lblSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        btnElegir.setBackground(new java.awt.Color(0, 0, 153));
        btnElegir.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btnElegir.setForeground(new java.awt.Color(255, 255, 255));
        btnElegir.setText("Elegir Combatientes");
        btnElegir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });
        getContentPane().add(btnElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 190, 40));

        btnGetDigimon.setBackground(new java.awt.Color(0, 0, 153));
        btnGetDigimon.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        btnGetDigimon.setForeground(new java.awt.Color(255, 255, 255));
        btnGetDigimon.setText("Obtener Digimon");
        btnGetDigimon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        btnGetDigimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDigimonActionPerformed(evt);
            }
        });
        getContentPane().add(btnGetDigimon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1a8b6a638a6d578d0e1b6aa96fde1017.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 490));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  

    public class mihilo extends Thread{
    public void inii( DefaultTableModel x){
            yggdrasill = new DigiWorld(x); 
        }
      
        @Override
      
        
        public void run() {
        try {
            yggdrasill.descargarDatos();
            yggdrasill.ordenar();
            Thread.sleep(100);
        } catch (IOException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnElegir.setEnabled(true);
        }
          
    
    }
    
    private void btnGetDigimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDigimonActionPerformed
       DigiWorld yggdrasill = new DigiWorld(model); 
        mihilo hilo= new mihilo();
        hilo.inii(model);
        hilo.start();
        btnGetDigimon.setEnabled(false);
    }//GEN-LAST:event_btnGetDigimonActionPerformed

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        estadio = new RumbleArena(); // un nuevo estadio para cada clic en el botón de batalla
        estadio.elegirDigimon(); // código de la clase para elegir a los digimon que pelearán
    }//GEN-LAST:event_btnElegirActionPerformed

    private void batallarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batallarActionPerformed
       // código para elegir un ganador en la batalla
        int nivel1=1, nivel2=1; // variables que representarán los niveles de los digimon
        System.out.println("Pelea en curso ...");
        // Peleador 1
        if (peleador1.getLevel().equals("Mega")) // nivel más alto
        nivel1 = 7;
        if (peleador1.getLevel().equals("Ultimate"))
        nivel1 = 6;
        if (peleador1.getLevel().equals("Champion"))
        nivel1 = 5;
        if (peleador1.getLevel().equals("Armor"))
        nivel1 = 4;
        if (peleador1.getLevel().equals("Rookie"))
        nivel1 = 3;
        if (peleador1.getLevel().equals("In Training"))
        nivel1 = 2;
        if (peleador1.getLevel().equals("Fresh")) // nivel más bajo
        nivel1 = 1;
        // Peleador 2
        if (peleador2.getLevel().equals("Mega"))
        nivel2 = 7;
        if (peleador2.getLevel().equals("Ultimate"))
        nivel2 = 6;
        if (peleador2.getLevel().equals("Champion"))
        nivel2 = 5;
        if (peleador2.getLevel().equals("Armor"))
        nivel2 = 4;
        if (peleador2.getLevel().equals("Rookie"))
        nivel2 = 3;
        if (peleador2.getLevel().equals("In Training"))
        nivel2 = 2;
        if (peleador2.getLevel().equals("Fresh"))
        nivel2 = 1;
        // Decisión de batalla
        // <Inserte su código aquí>
        System.out.println("¡Resultado de la batalla!");
        if(nivel1 > nivel2){
            JOptionPane.showMessageDialog(null,"Gano " + peleador1.getName());
        }else{
            JOptionPane.showMessageDialog(null,"Gano " + peleador2.getName());
        }
    }//GEN-LAST:event_batallarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
        System.out.println("LOGS:");
    }
    
    // clase para la hora del sistema. ¡No modificar!
    public class Reloj extends Thread {
        Calendar calendario;
        
        @Override
        public void run() {
            while (true) {
                calendario= Calendar.getInstance();
                if (calendario.get(Calendar.HOUR_OF_DAY)<10)
                    lblHH.setText(String.valueOf("0"+calendario.get(Calendar.HOUR_OF_DAY)) + " :");
                else
                    lblHH.setText(String.valueOf(calendario.get(Calendar.HOUR_OF_DAY)) + " :");
                if (calendario.get(Calendar.MINUTE)<10)
                    lblMM.setText(String.valueOf("0"+calendario.get(Calendar.MINUTE)) + " :");
                else
                    lblMM.setText(String.valueOf(calendario.get(Calendar.MINUTE)) + " :");
                if (calendario.get(Calendar.SECOND)<10)
                    lblSS.setText(String.valueOf("0"+calendario.get(Calendar.SECOND)) + " hrs");
                else
                    lblSS.setText(String.valueOf(calendario.get(Calendar.SECOND)) + " hrs");
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batallar;
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnGetDigimon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDigimon1;
    private javax.swing.JLabel lblDigimon2;
    private javax.swing.JLabel lblHH;
    private javax.swing.JLabel lblMM;
    private javax.swing.JLabel lblSS;
    private javax.swing.JTable tblDigimon;
    // End of variables declaration//GEN-END:variables
}
